
services:
  server_herbal:
    build: .
    container_name: server_herbal_dev
    volumes:
      - .:/app  # Sync host project dir into container
    ports:
      - "1201:1201"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run --reload
