version: '3.8'

services:
  server_herbal:
    build: .
    container_name: server_herbal_dev
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - MYSQL_HOST=${MYSQL_HOST:-127.0.0.1}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-herbal}
      - BASE_URL=${BASE_URL:-http://localhost:1201}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/app/app/static/uploads}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-super-secret-key}
    command: flask run --reload
    network_mode: host
