version: '3.8'

services:
  server_herbal:
    build: .
    container_name: server_herbal_dev
    volumes:
      - .:/app  
    ports:
      - "1201:1201"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-herbal_db}
    command: flask run --reload
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-herbal}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: